### ISSUE TITLE
blocked by CORS

### ISSUE THREAD

**Issue by Nicolas-Menettrier** [marion-vgv/ma-ville-au-vert#7]
J'ai voulu essayer le site après avoir vu le post sur linkedIn mais l'appel a l'api est bloqué par le CORS 

![image](https://user-images.githubusercontent.com/17987207/127325187-fc929430-36a1-46dc-9a20-906f3ea3edff.png)

**Comment by marion-vgv** [comment]
Merci de me l'avoir signalé ! Normalement, maintenant c'est réglé !

**Comment by Nicolas-Menettrier** [comment]
Top, il y a toujours l'erreur de connection au Websocket mais le site semble bien marcher la 💯
